// Todo el texto de la web, en español e inglés.
// Para editar un texto, cámbialo aquí en los dos idiomas.

export const PHONE_DISPLAY = "+34 674 002 395";
export const PHONE_RAW = "34674002395";
export const WHATSAPP_URL = `https://wa.me/${PHONE_RAW}`;
export const SOCIALS = {
  linkedin: "https://www.linkedin.com/in/desarrollador-ver%C3%B3nicac/",
  instagram: "https://www.instagram.com/veronicadev.web/",
  github: "https://github.com/VeronicaC-Fuentes",
};

export const CLIENTS = [
  { name: "Factor Barcelona", logo: "/logos/factor.png", w: 658, h: 150, height: 40 },
  { name: "Bresson Brokers", logo: "/logos/bresson.png", w: 620, h: 114, height: 32 },
  { name: "CFG Negocios Inmobiliarios", logo: "/logos/cfg.png", w: 657, h: 200, height: 42 },
  { name: "EPP Equipos de Protección Peruanos", logo: "/logos/epp.png", w: 389, h: 111, height: 44 },
  { name: "La Yapa", logo: "/logos/layapa.png", w: 720, h: 200, height: 32 },
  { name: "Investars Propiedades", logo: "/logos/investars.png", w: 760, h: 173, height: 40 },
];

// Proyectos. `home: true` aparece en la portada; todos aparecen en /portfolio.
export const PROJECTS = [
  {
    id: "factor",
    home: true,
    title: "Factor Barcelona",
    image: "/portfolio/factorbarcelona.jpg",
    url: "https://www.factorbarcelona.com/",
    stack: "Odoo 19 · Website · CRM",
    es: "Web corporativa en Odoo integrada con CRM, ventas y contabilidad, con automatizaciones comerciales a medida.",
    en: "Corporate website on Odoo integrated with CRM, sales and accounting, with custom sales automations.",
  },
  {
    id: "bresson",
    home: true,
    title: "Bresson",
    image: "/portfolio/bresson.jpg",
    url: "https://bresson.com.ar/",
    stack: "Node.js · Airtable · Tokko",
    es: "Sistema de reportes de propiedades automáticos con Puppeteer, Airtable y webhooks de Tokko, más optimización de la web.",
    en: "Automated property reporting system with Puppeteer, Airtable and Tokko webhooks, plus website performance work.",
  },
  {
    id: "cfg",
    home: true,
    title: "CFG Negocios Inmobiliarios",
    image: "/portfolio/cfg.jpg",
    url: "https://cfgnegociosinmobiliarios.com/",
    stack: "React · Supabase · Tokko",
    es: "Web inmobiliaria con CMS en Supabase, integración con Tokko CRM, buscador, fichas de propiedad, barrios y panel de administración.",
    en: "Real estate website with a Supabase CMS, Tokko CRM integration, search, property pages, neighbourhood pages and an admin panel.",
  },
  {
    id: "layapa",
    home: true,
    title: "La Yapa",
    image: "/portfolio/layapa.jpg",
    url: "https://www.layapa.es/",
    stack: "Odoo Website · eCommerce B2B",
    es: "Tienda online en Odoo para un distribuidor mayorista de productos argentinos en Europa, con catálogo y acceso para clientes B2B.",
    en: "Odoo online store for a wholesale distributor of Argentine products in Europe, with a catalogue and B2B customer access.",
  },
  {
    id: "odoo_credit",
    title: "Restricciones de crédito",
    image: "/portfolio/odoo-restricciones-1.png",
    url: "https://github.com/VeronicaC-Fuentes/Modulos_personalizados_Odoo_17",
    stack: "Odoo 17 · Python · PostgreSQL",
    es: "Módulos backend en Odoo.sh para un distribuidor de EPP en Perú: validación automática de líneas de crédito y bloqueos en el flujo de venta.",
    en: "Backend modules on Odoo.sh for a PPE distributor in Peru: automatic credit-line validation and blocks in the sales flow.",
  },
  {
    id: "giuni",
    title: "Inmobiliaria Giuni",
    image: "/portfolio/giuni-cartagena.png",
    url: "https://www.inmobiliariagiunicartagena.com/",
    stack: "Odoo 18 Website · OWL",
    es: "Web inmobiliaria conectada en tiempo real con Odoo.",
    en: "Real estate website connected to Odoo in real time.",
  },
  {
    id: "epp",
    title: "Equipos de Protección",
    image: "/portfolio/eppweb.jpg",
    url: "https://www.equiposdeproteccion.pe/",
    stack: "Next.js · Tailwind CSS",
    es: "Catálogo online de equipos de protección personal.",
    en: "Online catalogue of personal protective equipment.",
  },
  {
    id: "odoo_contacts",
    title: "Validación de contactos",
    image: "/portfolio/odoo-contacts-1.png",
    url: "https://github.com/VeronicaC-Fuentes/Modulos_personalizados_Odoo_17/tree/main/contacts_form",
    stack: "Odoo 17 · Python · XML",
    es: "Módulo de gestión y validación de datos de contactos (RUC/DNI).",
    en: "Contact data management and validation module (RUC/DNI).",
  },
  {
    id: "thehub",
    title: "The Hub",
    image: "/portfolio/thehub.jpg",
    url: "https://thehubentertainment.pe/",
    stack: "Next.js · React · TypeScript",
    es: "Web corporativa para una agencia de entretenimiento y medios.",
    en: "Corporate website for an entertainment and media agency.",
  },
  {
    id: "gasyproyectos",
    title: "Gas y Proyectos",
    image: "/portfolio/gasyproyectos.jpg",
    url: "https://gasproyectosperu.com/",
    stack: "Next.js · Tailwind CSS",
    es: "Web institucional para una empresa de ingeniería y gas.",
    en: "Company website for an engineering and gas firm.",
  },
];

export const CONTENT = {
  es: {
    nav: { services: "Servicios", process: "Cómo trabajamos", projects: "Proyectos", about: "Sobre mí", cta: "Agenda una llamada", lang: "EN" },
    callText: "Hola Verónica, me gustaría agendar una llamada.",
    hero: {
      eyebrow: "Desarrolladora full-stack · Especialista en Odoo",
      title: ["Hago que la tecnología trabaje", "para ti."],
      lead: "Soy Verónica Cruces. Desarrollo aplicaciones y webs a medida, integro tus herramientas y automatizo procesos. Mi especialidad: Odoo.",
      primary: "Cuéntame tu proyecto",
      secondary: "Ver proyectos",
      alt: "Verónica Cruces apoyada en una gran puerta verde de madera",
    },
    clients: "Han confiado en mí",
    services: {
      label: "Servicios",
      title: ["Lo que puedo hacer", "por tu empresa"],
      lead: "Consultoría, desarrollo e integración. Trabajo por proyecto cerrado o bolsa de horas.",
      forLabel: "Para ti si",
      newLabel: "Nuevo",
      items: [
        { title: "Consultoría tecnológica", isNew: true, featured: true, for: "vas a invertir en software y quieres decidir bien, o ya lo tienes y no le sacas partido.", list: ["Diagnóstico de tu operación y tus sistemas", "Auditoría de tu instancia Odoo", "Hoja de ruta con prioridades y costes", "Acompañamiento mensual"], tech: "Odoo · Procesos · Arquitectura" },
        { title: "Integraciones & automatización", isNew: true, for: "tu equipo copia datos a mano entre herramientas o hace los mismos reportes cada semana.", list: ["Conexión entre sistemas vía API", "Webhooks y sincronización de datos", "Reportes y documentos automáticos", "Alertas y flujos sin intervención"], tech: "REST · Webhooks · Node.js · Tokko · Airtable · Google Ads" },
        { title: "Aplicaciones a medida", for: "necesitas una herramienta que no existe en el mercado: un portal, un panel o una app interna.", list: ["Paneles de administración y portales", "Backend, base de datos y usuarios", "Integración con tu ERP o CRM", "Despliegue y mantenimiento"], tech: "React · Next.js · Node.js · Supabase · PostgreSQL" },
        { title: "Implementación Odoo", for: "quieres ordenar ventas, CRM, inventario o formación en un solo sistema.", list: ["Configuración de módulos", "Migración de datos", "Permisos y flujos por rol", "Formación a tu equipo"], tech: "Odoo 17 · 18 · 19 · Odoo.sh · Odoo Online" },
        { title: "Desarrollo Odoo", for: "Odoo cubre casi todo, pero te falta esa funcionalidad clave para tu negocio.", list: ["Módulos a medida", "Reglas de negocio y validaciones", "Reportes PDF y vistas propias", "Corrección de errores y mejoras"], tech: "Python · OWL · XML · QWeb · PostgreSQL" },
        { title: "Web, e-commerce & SEO", for: "tu web es lenta, no aparece en Google o no está conectada con tu negocio.", list: ["Webs corporativas y tiendas online", "Optimización de velocidad (WPO)", "SEO técnico y analítica", "Mantenimiento evolutivo"], tech: "Odoo Website · WordPress · Next.js · Search Console" },
      ],
      stackTitle: "Stack técnico",
      stackSub: "Las herramientas con las que trabajo a diario.",
      stack: [["ERP", "Odoo 17 · 18 · 19"], ["Backend", "Python · Node.js"], ["Frontend", "React · Next.js · OWL"], ["Datos", "PostgreSQL · Supabase · Airtable"], ["Integraciones", "REST APIs · Webhooks"], ["Web", "WordPress · Tailwind · SEO"]],
      ctaText: ["¿No sabes cuál necesitas?", "Empecemos por una consultoría."],
    },
    strip: ["Consultoría", "Integraciones API", "Automatización", "Apps a medida", "Odoo", "React · Next.js", "SEO técnico"],
    process: {
      label: "Cómo trabajamos",
      title: ["Un proceso claro,", "de principio a fin."],
      lead: "Sabes en todo momento en qué fase estamos, qué viene después y cuánto cuesta.",
      alt: "Verónica con un cuaderno en la mano, apoyada en una columna de granito",
      steps: [["Diagnóstico", "Entiendo tu operación y lo que necesitas."], ["Propuesta", "Alcance, fases y presupuesto claros."], ["Desarrollo", "Construyo y pruebo contigo en cada fase."], ["Puesta en marcha", "Lanzamiento y formación a tu equipo."]],
      modesTitle: "Modalidades",
      modes: [
        { title: "Asesoría puntual", desc: "Una sesión para revisar tu caso y salir con un plan claro.", list: ["Videollamada", "Resumen con recomendaciones"], price: "A consultar" },
        { title: "Proyecto cerrado", desc: "Alcance, fases y precio definidos antes de empezar.", list: ["Presupuesto por fases", "Entregas y pruebas"], price: "Presupuesto a medida", inv: true },
        { title: "Acompañamiento mensual", desc: "Bolsa de horas para soporte, mejoras y evolución continua.", list: ["Soporte prioritario", "Mejoras cada mes"], price: "A consultar" },
      ],
    },
    projects: { label: "Proyectos", title: ["Trabajo", "reciente"], all: "Ver portafolio completo", view: "Ver web" },
    about: {
      label: "Sobre mí",
      title: ["Tecnología al servicio de", "cómo trabaja tu empresa."],
      p1: "Soy Verónica Cruces, desarrolladora full-stack y consultora Odoo. Desde 2023 acompaño a empresas de España y Latinoamérica con su tecnología.",
      p2: "Mi trabajo va desde módulos a medida en Odoo hasta aplicaciones en React y Node.js, webs, integraciones y automatizaciones que conectan todas las herramientas de un negocio. Trabajo en remoto, como nómada digital.",
      p3: "Antes de proponer nada, entiendo cómo funciona tu operación. Te explico con claridad qué conviene configurar, qué conviene desarrollar y qué no hace falta. Cuando trabajas conmigo, hablas directamente con quien diseña y programa la solución.",
      alts: ["Verónica con blazer negro apoyada en una fachada de piedra", "Verónica apoyada con el brazo en una pared, en una calle estrecha", "Verónica mirando hacia arriba en una calle del casco histórico"],
    },
    reviews: {
      label: "Recomendaciones",
      title: ["Lo que dicen", "mis clientes"],
      ask: "¿Ya trabajamos juntos? Tu opinión me ayuda mucho.",
      askBtn: "Déjame tu reseña en Google",
      googleUrl: null,
      alt: "Verónica tapándose la cara con un libro abierto, sonriendo",
      // Añade aquí reseñas reales de Google: { text, name, role }
      items: [],
    },
    band: { label: "Mi forma de trabajar", text: ["Tecnología que simplifica, conecta áreas y ayuda a", "decidir mejor."], alt: "Verónica con blazer negro frente a una puerta verde entre muros de granito" },
    contact: {
      label: "Contacto",
      title: "¿Hablamos?",
      lead: "Cuéntame qué necesitas y te respondo con los próximos pasos.",
      call: "Agenda una llamada",
      phone: "Teléfono",
      copy: "Copiar",
      copied: "Copiado",
      alt: "Verónica sonriendo frente a un muro de piedra",
    },
    portfolio: { title: ["Portafolio", "completo"], lead: "Webs, aplicaciones, integraciones y módulos Odoo que he desarrollado.", back: "Volver al inicio" },
    whatsappAria: "Escríbeme por WhatsApp",
    swipe: "Desliza",
  },
  en: {
    nav: { services: "Services", process: "How I work", projects: "Projects", about: "About", cta: "Book a call", lang: "ES" },
    callText: "Hi Verónica, I'd like to book a call.",
    hero: {
      eyebrow: "Full-stack developer · Odoo specialist",
      title: ["I make technology work", "for you."],
      lead: "I'm Verónica Cruces. I build custom apps and websites, connect your tools and automate processes. My specialty: Odoo.",
      primary: "Tell me about your project",
      secondary: "See projects",
      alt: "Verónica Cruces leaning on a large green wooden door",
    },
    clients: "Trusted by",
    services: {
      label: "Services",
      title: ["What I can do", "for your company"],
      lead: "Consulting, development and integration. Fixed-price projects or hour packs.",
      forLabel: "For you if",
      newLabel: "New",
      items: [
        { title: "Technology consulting", isNew: true, featured: true, for: "you're about to invest in software and want to decide well, or you already have it and aren't getting the most out of it.", list: ["Review of your operations and systems", "Audit of your Odoo instance", "Roadmap with priorities and costs", "Monthly support"], tech: "Odoo · Processes · Architecture" },
        { title: "Integrations & automation", isNew: true, for: "your team copies data by hand between tools or builds the same reports every week.", list: ["System-to-system API connections", "Webhooks and data sync", "Automatic reports and documents", "Hands-off alerts and workflows"], tech: "REST · Webhooks · Node.js · Tokko · Airtable · Google Ads" },
        { title: "Custom applications", for: "you need a tool that doesn't exist off the shelf: a portal, a dashboard or an internal app.", list: ["Admin panels and portals", "Backend, database and users", "Integration with your ERP or CRM", "Deployment and maintenance"], tech: "React · Next.js · Node.js · Supabase · PostgreSQL" },
        { title: "Odoo implementation", for: "you want sales, CRM, inventory or training organised in one system.", list: ["Module configuration", "Data migration", "Role-based permissions and flows", "Team training"], tech: "Odoo 17 · 18 · 19 · Odoo.sh · Odoo Online" },
        { title: "Odoo development", for: "Odoo covers almost everything, but you're missing that one key feature for your business.", list: ["Custom modules", "Business rules and validations", "Custom PDF reports and views", "Bug fixes and improvements"], tech: "Python · OWL · XML · QWeb · PostgreSQL" },
        { title: "Web, e-commerce & SEO", for: "your website is slow, doesn't show up on Google or isn't connected to your business.", list: ["Corporate websites and online stores", "Speed optimisation", "Technical SEO and analytics", "Ongoing maintenance"], tech: "Odoo Website · WordPress · Next.js · Search Console" },
      ],
      stackTitle: "Tech stack",
      stackSub: "The tools I work with every day.",
      stack: [["ERP", "Odoo 17 · 18 · 19"], ["Backend", "Python · Node.js"], ["Frontend", "React · Next.js · OWL"], ["Data", "PostgreSQL · Supabase · Airtable"], ["Integrations", "REST APIs · Webhooks"], ["Web", "WordPress · Tailwind · SEO"]],
      ctaText: ["Not sure which one you need?", "Let's start with a consultation."],
    },
    strip: ["Consulting", "API integrations", "Automation", "Custom apps", "Odoo", "React · Next.js", "Technical SEO"],
    process: {
      label: "How I work",
      title: ["A clear process,", "from start to finish."],
      lead: "You always know which phase we're in, what comes next and what it costs.",
      alt: "Verónica holding a notebook, leaning on a granite column",
      steps: [["Discovery", "I get to know your operations and needs."], ["Proposal", "Clear scope, phases and budget."], ["Development", "I build and test with you at every phase."], ["Launch", "Go-live and training for your team."]],
      modesTitle: "Ways to work together",
      modes: [
        { title: "One-off consultation", desc: "A session to review your case and leave with a clear plan.", list: ["Video call", "Written recommendations"], price: "On request" },
        { title: "Fixed-price project", desc: "Scope, phases and price agreed before we start.", list: ["Budget by phases", "Deliveries and testing"], price: "Custom quote", inv: true },
        { title: "Monthly support", desc: "An hour pack for support, improvements and ongoing evolution.", list: ["Priority support", "Monthly improvements"], price: "On request" },
      ],
    },
    projects: { label: "Projects", title: ["Recent", "work"], all: "See full portfolio", view: "Visit site" },
    about: {
      label: "About",
      title: ["Technology that serves", "the way your company works."],
      p1: "I'm Verónica Cruces, a full-stack developer and Odoo consultant. Since 2023 I've been helping companies in Spain and Latin America with their technology.",
      p2: "My work ranges from custom Odoo modules to React and Node.js applications, websites, integrations and automations that connect all of a business's tools. I work remotely, as a digital nomad.",
      p3: "Before proposing anything, I get to know how your operation works. I'll tell you clearly what to configure, what to build and what you don't need. When you work with me, you talk directly to the person who designs and codes the solution.",
      alts: ["Verónica in a black blazer leaning on a stone façade", "Verónica leaning her arm on a wall in a narrow street", "Verónica looking up in an old-town street"],
    },
    reviews: {
      label: "Reviews",
      title: ["What my clients", "say"],
      ask: "Have we worked together? Your feedback means a lot.",
      askBtn: "Leave me a Google review",
      googleUrl: null,
      alt: "Verónica hiding her face behind an open book, smiling",
      items: [],
    },
    band: { label: "How I like to work", text: ["Technology that simplifies, connects teams and helps you", "decide better."], alt: "Verónica in a black blazer in front of a green door between granite walls" },
    contact: {
      label: "Contact",
      title: "Let's talk",
      lead: "Tell me what you need and I'll get back to you with next steps.",
      call: "Book a call",
      phone: "Phone",
      copy: "Copy",
      copied: "Copied",
      alt: "Verónica smiling in front of a stone wall",
    },
    portfolio: { title: ["Full", "portfolio"], lead: "Websites, applications, integrations and Odoo modules I've built.", back: "Back to home" },
    whatsappAria: "Message me on WhatsApp",
    swipe: "Swipe",
  },
};
